<div class="container">
    <section id="container-tabela"> <!-- Tabela para listagem de clientes -->
        <table id="tableClientes" class="table table-striped table-bordered " style="width:100%">

            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Cpf</th>
                    <th>Telefone</th>
                    <th>Email</th>
                    <th>Cidade</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach($this->view->clientes as $cliente){ ?>
                    <tr>
                        <td><?= $cliente->nome ?></td>
                        <td><?= $cliente->cpf ?></td>
                        <td><?= $cliente->telefone ?></td>
                        <td><?= $cliente->email ?></td>
                        <td><?= $cliente->cidade ?></td>
                        <td><button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#editarCliente"  onclick="editarCliente('<?= $cliente->cpf ?>')">Editar</button></td>
                        <td><button class="btn btn-sm btn-danger" onclick="removerCliente('<?= $cliente->cpf ?>')">Remover</button></td>
                    </tr>
                <?php } ?>
            
            </tbody>

        </table>
    </section>
</div>

