<!------------------------ Alertas em casos de erros ----------------------->

<?php if(isset($_GET['status']) && $_GET['status'] == 0){ ?>
    <div class="alert alert-danger mt-2" role="alert">
    <p>Erro ao inserir novo cliente. </p> 
    <p> Dica: verifique se o CPF já não é existente!</p>
    </div>
<?php } ?>

<?php if(isset($_GET['status']) && $_GET['status'] == 1){ ?>
    <div class="alert alert-success mt-2" role="alert">
        Cliente cadastrado com sucesso!
    </div>
<?php } ?>


<div class="container">

    <div class="area-acoes">
        <span class="titulo">Listagem de clientes cadastrados</span>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#novoCliente">Novo cliente</button>
    </div>

    <section id="container-tabela"> <!-- Tabela para listagem de clientes -->
        <table id="tableClientes" class="table table-striped table-bordered " style="width:100%">

            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Cpf</th>
                    <th>Telefone</th>
                    <th>Email</th>
                    <th>Estado</th>
                    <th>Cidade</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach($this->view->clientes as $cliente){ ?>
                    <tr>
                        <td><?= $cliente->nome ?></td>
                        <td><?= $cliente->cpf ?></td>
                        <td><?= $cliente->telefone ?></td>
                        <td><?= $cliente->email ?></td>
                        <td><?= $cliente->estado ?></td>
                        <td><?= $cliente->cidade ?></td>
                        <td><button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#editarCliente"  onclick="editarCliente('<?= $cliente->cpf ?>')">Editar</button></td>
                        <td><button class="btn btn-sm btn-danger" onclick="removerCliente('<?= $cliente->cpf ?>')">Remover</button></td>
                    </tr>
                <?php } ?>
            
            </tbody>

        </table>
    </section>


    
    <!-- Modal para criar novo cliente -->

    <div class="modal fade" id="novoCliente" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

        <div class="modal-dialog modal-lg" role="document">

            <div class="modal-content">

                <form method="POST" action="/cadastrarNovoCliente">

                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Novo cliente</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                
                    <div class="modal-body">

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Nome</label>
                                <input type="text" class="form-control" placeholder="Nome" name="nome" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">CPF</label>
                                <input type="text" class="form-control" placeholder="CPF" name="cpf" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">RG</label>
                                <input type="text" class="form-control" placeholder="RG" name="rg" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Telefone</label>
                                <input type="tel" class="form-control" placeholder="Telefone" name="telefone" required>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="inputEmail4">Email</label>
                                <input type="email" class="form-control" placeholder="Email" name="email" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputEstado">Estado</label>
                                <select id="inputEstado" class="form-control"  name="estado" required>
                                <option selected>Escolher...</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputCidade">Cidade</label>
                                <select id="inputCidade" disabled class="form-control" name="cidade" required>
                                    <option selected>Escolha um estado...</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputEstado">Logradouro</label>
                                <input type="text" class="form-control" placeholder="Logradouro" name="logradouro" required>
                            </div>
                            <div class="form-group col-md-3">
                                <label for="inputCidade">Número</label>
                                <input type="text" class="form-control" placeholder="Número" name="numero" required>
                            </div>
                            <div class="form-group col-md-3">
                                <label for="inputCidade">Bairro</label>
                                <input type="text" class="form-control" placeholder="Bairro"  name="bairro" required>
                            </div>

                        </div><!-- Fim do row-form -->

                    </div><!-- Fim do modal-body -->

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                        <button type="sumbit" id="botaoEnviar" class="btn btn-primary">Cadastrar</button>
                    </div>

                </form>

            </div><!--Fim modal content -->

        </div><!--Fim modal dialog -->

    </div>

    <!-- Modal para editar cliente -->
    
    <div class="modal fade" id="editarCliente" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

        <div class="modal-dialog modal-lg" role="document">

            <div class="modal-content">

                <form method="POST" action="/atualizarCliente">

                    <div class="modal-header">
                        <h5 class="modal-title">Editar cliente</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                
                    <div class="modal-body"></div><!-- Fim do modal-body -->

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                        <button type="sumbit" id="botaoAtualizarCliente" class="btn btn-primary">Atualizar</button>
                    </div>

                </form>

            </div><!--Fim modal content -->

        </div><!--Fim modal dialog -->

    </div>

    

</div>

